17714 - [Updater] McLaren Kaohsiung error
klnmi97/Squirrel.Windows pull request #14
Opened 2021-10-27 13:59 UTC by petrca

2021-10-27 15:02 UTC, ArosPrince requested changes

2021-10-27 15:02 UTC, ArosPrince commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    // This might happen if we got killed partially through copying to a temporary installation directory.
```suggestion
                    // This might happen if we got killed while copying to a temporary installation directory.
```

2021-10-27 15:02 UTC, ArosPrince commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    .Where(x => !x.Name.StartsWith("tmp-")); // Skip, it is not old version folder, we want to delete it in installPackageToAppDir.
Don't understand the comment, can you elaborate?

2021-10-27 15:02 UTC, ArosPrince commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    // first because it takes a while and there is a chance that it could be interrupted (e.g. machine shutdown).
```suggestion
                    // Copies application to a temporary installation directory. We copy it to the temporary directory first,
                    // because it takes a while and there is a chance that it could be interrupted (e.g. machine shutdown).
```

2021-11-01 08:42 UTC, klnmi97 approved these changes
Seems to be a fine solution after resolving @ArosPrince 's comments

2021-11-02 14:01 UTC, petrca commented on src/Squirrel/UpdateManager.ApplyReleases.cs
> +                    .Where(x => !x.Name.StartsWith("tmp-")); // Skip, it is not old version folder, we want to delete it in installPackageToAppDir.
This function removes old app versions before installing a new one. I've added this condition to not delete folders starting with "tmp-" which can persist there when user somehow interrupts update process. I want to delete it later in the _installPackageToAppDir_ (with appropriate log) which is responsible for this directory creation.

2021-11-02 14:53 UTC, ArosPrince approved these changes

2021-11-02 15:21 UTC, merged